### ISSUE TITLE
Formating enhancement

### ISSUE THREAD

**Issue by jullimullins** [platon-ivanov/obsidian-heading-counter#2]
Add option to format heading numbers to be part of the heading.
Current:
   1. Headign 1
1.1  Heading 2

Proposed
1. Heading 1
1.1 Heading 2

Code changes need:
var baseTheme = import_view.EditorView.baseTheme({
  ".cm-header-count": {
    //position: "absolute",
    //transform: "translateX(calc(-100% - 0.0rem))",
    opacity: 0.5
  }

And:
  }
  toDOM(view) {
    const div = document.createElement("span");
    div.innerText = this.count;
	div.innerText = div.innerText + " "
    div.classList.add("cm-header-count");
    return div;
  }

**Comment by platon-ivanov** [comment]
Hello! Thank you for your suggestion, the [current version](https://github.com/platon-ivanov/obsidian-heading-counter/releases/tag/v1.2.0) doesn't have the absolute positioning anymore.
