### ISSUE TITLE
Numbering in outline pane

### ISSUE THREAD

**Issue by DutchPete** [platon-ivanov/obsidian-heading-counter#5]
The objective of numbering the headings is to make navigation in a document easier, particularly in a long one.

The other aspect of document navigation is the Outline pane, which is one of the core plug-ins.

For a best document navigation experience the heading numbers seen in the text should also be shown in the Outline.

I know that the numbers in the text are virtual only, they are not part of the document. However, Typora does manage it with CSS, as I pointed out in the forum page.

**Comment by xung** [comment]
need this feature too.

**Comment by platon-ivanov** [comment]
The new version counts headings in the outline, although it doesn't heed the start level setting.

**Comment by DutchPete** [comment]
Heyyy, you are almost there!

At my end it does heed the start level, and clicking on a heading in the Outline does take the cursor to that heading, which is an amazing achievement! Thanks a lot.

But there are 2 points still off:

- the plug-in adds a number before the real number, usually it adds a 1
- it does not go deeper than H2 headings.

**Comment by platon-ivanov** [comment]
@DutchPete, thank you for the points. Could you try with the [latest version](https://github.com/platon-ivanov/obsidian-heading-counter/releases/tag/v1.3.1)?

![image](https://user-images.githubusercontent.com/100810261/208435450-6a03a674-49df-4085-8ef6-8bd95d47505a.png)

**Comment by DutchPete** [comment]
You sir, are a star!! You have cracked it indeed.
All headers of all levels are shown in the Outline pane, with the right numbers and all are clickable. And when I disable the plug-in the numbers are gone, as they should.
Many thanks for your patience and perseverance 🙏

You should now get it into the community store, and make sure people are aware of it.

**Comment by DutchPete** [comment]
There is 1 minor issue I noticed just now:

![image](https://user-images.githubusercontent.com/10794265/208491899-ba6668d7-a363-426e-be70-b1c81bd3d068.png)

The vertical alignment of 8.4 is not right. And although 8.2 and 8.3 appear to be aligned with one another, if I expand 8.2 you can see that alignment is not right:

![image](https://user-images.githubusercontent.com/10794265/208492142-4c71eb75-da28-4c76-b6f2-540c41ff8e08.png)

**Comment by platon-ivanov** [comment]
The only thing the plugin does is counting and inserting the numbers before the already existing text. Jumping to headings on click is actually built-in Obsidian behavior! Therefore even this styling misalignment is built-in. It's caused by headings having subheadings and therefore needing a folding arrow.

![image](https://user-images.githubusercontent.com/100810261/208523494-8df2a500-8003-4c35-be8d-12351b8c72f3.png)

If you'd like to make the headings inline, you can add this CSS snippet.

```css
.tree-item-inner {
	padding-left: var(--size-4-3);
}

.tree-item-icon {
	position: absolute;
}
```

![image](https://user-images.githubusercontent.com/100810261/208532400-5cbfd821-9e23-4505-90ba-c0d54b0331c8.png)

I would like to make it cleaner using the `:has()` pseudo-class, but unfortunately Obsidian is running on Chrome 100, which didn't support it yet.

**Comment by DutchPete** [comment]
Yes, that works, thanks a lot!

**Comment by platon-ivanov** [comment]
This snipped was added to the [new version](https://github.com/platon-ivanov/obsidian-visually-numbered-headings/releases/tag/1.3.2). It really looks nicer that way. Thank you @DutchPete!

**Comment by DutchPete** [comment]
Yes, that works fine now.

So, Platon, you have now cleaned, polished, and completed the plug-in. Well done!!
I am very happy with it, this is what I was looking for.

I noticed you have submitted it to the Obsidian devs for inclusion in the community repository. In my opinion it should a togglable core plug-in of Obsidian, but that is not for me to decide.

Anyway, thanks again.

**Comment by rufft** [comment]
не, ну это лайк, автор ты лучший!

**Comment by rufft** [comment]
谢谢你的工作，党为你感到骄傲!
