### ISSUE TITLE
Plugin name change

### ISSUE THREAD

**Issue by imed-ghomari** [platon-ivanov/obsidian-heading-counter#7]
Hello, big fan of the idea of this plugin. Previously, I was using the plugin [number headings plugin](https://github.com/onlyafly/number-headings-obsidian). 

Don't you think it's confusing that the two plugin names are so similar? Maybe change it to `Visual numbered heading` or something similar to differentiate between the two plugins when it's available in the obsidian community plugin store.

**Comment by platon-ivanov** [comment]
I agree with this. I changed the plugin name and created a new pull request for the Obsidian community plugin list. Thank you!

**Comment by DutchPete** [comment]
I did not see this announcement, so I was really confused when I wanted to enable it after installing the latest version and I did not see it in its usual place in the plug-in list in the Obs settings. Eventually I scrolled down to the end of the list and found it 🤣
